---
# deploy.yml includes deployment stuffs

# Roles defined for People service application

- hosts: ansiblenode 
  remote_user: vagrant
  become: true
  roles:
    - { role: dps, when: app_name == "dps" }
