---
# defaults file for DPS application

APP: '{{ app_name }}'
JAVA_LOC_ORIG: '/usr/jdk/jdk1.8.0_131'
env_full_fillment: 'DEV-Development'
PROCESS_NAME: sendmail
APP_PROGRAM_FILE: '/usr/lib/sendmail'
svn_trunk_url: 'https://github.com/johnbashas/Ansible/blob/master'
APP_PORT: 25

#Application file and directory description
UID: P639861
TEMP: '/tmp/{{ UID }}/dps'
DPS_HOME: '/tmp/{{UID }}/local/apps/dps'
#HOME_DPS: '/tmp/{{ UID }}/local/apps/dps'
DPS_APP_HOME: '{{ DPS_HOME }}/{{ APP }}'
DPS_DIST_DIR: '{{ DPS_HOME }}/dist'
DPS_DEPLOY_DIR: '{{ DPS_HOME }}/deploy'
DPS_LOG_DIR: '{{ DPS_APP_HOME }}/logs'
BUILD_CONFIRMATION_FILE: '{{ DPS_DEPLOY_DIR }}/bin/build.info'
DPS_APP_LOG_FILE: '{{ DPS_LOG_DIR }}/{{ APP }}.log'
#APP_PROGRAM_FILE: '{{ APP_HOME }}/bin/{{ APP }}.jar'

#User details
APP_OWNER: 'vagrant'
APP_GROUP: 'vagrant'

#Extra vars description
java_loc_orig: '{{ JAVA_LOC_ORIG }}'
dps_var_file_name: 'dump_all_vars_dev_dps.txt'

#Email description
email_attachment_success: "{{ DPS_LOG_DIR }}/{{ APP }}_{{ dps_new_build }}_{{ deploy_start_time }}.log"
email_subject_success: "Deployment Log for {{APP}}"
email_body_success: "Deployment completed for {{APP}} on {{ env_full_fillment }}, Log file : {{ DPS_LOG_DIR }}/{{ APP }}_{{ dps_new_build }}_{{ deploy_start_time }}.log"
DIST_LIST_success: 'basha.tech@gmail.com'

email_attachment_failed: "/tmp/{{ UID }}/local/apps/dps/dist/*.log"
email_subject_failed: "Deployment Failure Log for {{APP}}"
email_body_failed: "Deployment failed for {{APP}} on {{ env_full_fillment }}, Log file : {{ DPS_LOG_DIR }}/Failed_Log_{{ APP }}_{{ deploy_start_time }}.log"
DIST_LIST_failed: 'basha.tech@gmail.com'

MAIL_PORT: 25
